import React from "react"
const motoDatos = [
    {
      "Marca": "Honda",
      "modelo": "ADV150",
      "año": "2022",
      "tipo": "Scooter",
      "cilindrada": "149,0 ccm (9,09 pulgadas cúbicas)",
      "motor": "monocilíndrico, cuatro tiempos",
      "compresión": "10.6:1",
      "diámetro_carrera": "57,3 x 57,9 mm (2,3 x 2,3 pulgadas)",
      "válvulas_por_cilindro": "2",
      "sistema_combustible": "Inyección. PGM-FI; cuerpo de mariposa de 26 mm",
      "control_combustible": "Levas en cabeza simples (SOHC)",
      "ignición": "Completamente transistorizado",
      "refrigeración": "Líquido",
      "caja de cambios": "automática",
      "transmisión": "Correa (transmisión final)",
      "suspensión_delantera": "Horquilla telescópica Showa® de 31 mm",
      "recorrido_rueda_delantera": "130 mm (5,1 pulgadas)",
      "rear_suspension": "Amortiguadores dobles Showa®",
      "recorrido_rueda_trasera": "119 mm (4,7 pulgadas)",
      "neumático_delantero": "110/80-14 ",
      "neumático_trasero": "130/70-13 ",
      "frenos_delanteros": "Disco simple. ABS. ",
      "frenos_traseros": "Disco simple. ABS",
      "peso_seco": "133,4 kg (294,0 libras)",
      "seat_height": "795 mm (31,3 pulgadas) Si es ajustable, el ajuste más bajo",
      "altura_total": "1153 mm (45,4 pulgadas)",
      "longitud_total": "1950 mm (76,8 pulgadas)",
      "ancho_total": "763 mm (30.0 inches)",
      "distancia_al suelo": "165 mm (6,5 pulgadas)",
      "distancia entre ejes": "1323 mm (52,1 pulgadas)",
      "capacidad_combustible": "8.00 litros (2.11 galones US)",
      "arranque": "Eléctrico"
    },
    {
      "Marca": "Honda",
      "modelo": "ADV350",
      "año": "2022",
      "tipo": "Scooter",
      "cilindrada": "330,0 ccm (20,14 pulgadas cúbicas)",
      "motor": "monocilíndrico, cuatro tiempos",
      "potencia": "28,8 CV (21,0 kW)) @ 7500 RPM",
      "par": "31,9 Nm (3,3 kgf-m o 23,5 ft.lbs) @ 5250 RPM",
      "compresión": "10.5:1",
      "diámetro_carrera": "77,0 x 70,8 mm (3,0 x 2,8 pulgadas)",
      "válvulas_por_cilindro": "4",
      "sistema_combustible": "Inyección. PGM-FI; cuerpo de mariposa de 26 mm",
      "control_combustible": "Levas en cabeza simples (SOHC)",
      "ignición": "Encendido transistorizado completo",
      "refrigeración": "Líquido",
      "caja de cambios": "Automática",
      "transmisión": "Correa (transmisión final)",
      "embrague": "\t Embrague centrífugo automático; tipo seco",
      "consumo_combustible": "3,40 litros/100 km (29,4 km/l o 69,18 mpg)",
      "emission": "78,9 g/km de CO2 (CO2 - Emisión de dióxido de carbono) ",
      "bastidor": "bajos de acero",
      "suspensión_delantera": "37mm Upside down forks",
      "recorrido_rueda_delantera": "125 mm (4,9 pulgadas)",
      "suspensión_trasera": "Twin shocks",
      "recorrido_rueda_trasera": "130 mm (5,1 pulgadas)",
      "neumático_delantero": "120/70-15 ",
      "neumático_trasero": "140/70-14 ",
      "frenos_delanteros": "Disco simple. ABS. Pinza Nissin de 2 pistones",
      "frenos_traseros": "Single disc",
      "peso_en_seco": "186,0 kg (410,1 libras)",
      "altura_asiento": "795 mm (31,3 pulgadas) Si es ajustable, la posición más baja",
      "altura_total": "1430 mm (56,3 pulgadas)",
      "longitud_total": "2200 mm (86,6 pulgadas)",
      "ancho_total": "895 mm (35.2 inches)",
      "distancia_al suelo": "145 mm (5,7 pulgadas)",
      "distancia entre ejes": "1520 mm (59,8 pulgadas)",
      "capacidad_combustible": "11,70 litros (3,09 galones US)",
      "arranque": "Eléctrico"
    },
    {
      "Marca": "Honda",
      "modelo": "Ace 125",
      "año": "2022",
      "tipo": "Allround",
      "cilindrada": "124,1 ccm (7,57 pulgadas cúbicas)",
      "motor": "V2, cuatro tiempos",
      "potencia": "8,5 CV (6,2 kW)) @ 6500 RPM",
      "par": "10,1 Nm (1,0 kgf-m o 7,5 ft.lbs) @ 5000 RPM",
      "compresión": "9.4:1",
      "diámetro_carrera": "44,0 x 41,0 mm (1,7 x 1,6 pulgadas)",
      "control_combustible": "Válvulas en cabeza (OHV)",
      "refrigeración": "Aire",
      "caja de cambios": "4 velocidades",
      "transmisión": "Cadena (transmisión final)",
      "bastidor": "Diamante, acero",
      "suspensión_delantera": "Horquilla telescópica de 31 mm, 130 mm de recorrido del eje",
      "suspensión_trasera": "Basculante Pro-Link",
      "neumático_delantero": "80/100-18 ",
      "neumático_trasero": "90/90-18 ",
      "frenos_delanteros": "Freno de expansión (freno de tambor)",
      "frenos_traseros": "Freno expansible",
      "peso_seco": "110,0 kg (242,5 libras)",
      "altura_asiento": "790 mm (31,1 pulgadas) Si es ajustable, la posición más baja",
      "altura_total": "1059 mm (41,7 pulgadas)",
      "longitud_total": "2050 mm (80,7 pulgadas)",
      "total_width": "751 mm (29.6 inches)",
      "distancia_al suelo": "155 mm (6.1 inches)",
      "distancia entre ejes": "1310 mm (51,6 pulgadas)",
      "capacidad_combustible": "10.00 litros (2.64 galones US)",
      "arranque": "Kick"
    },
    {
      "marca": "Honda",
      "modelo": "Activa",
      "año": "2022",
      "tipo": "Scooter",
      "cilindrada": "109,1 ccm (6,66 pulgadas cúbicas)",
      "motor": "monocilíndrico, cuatro tiempos",
      "potencia": "7,7 CV (5,6 kW)) @ 8000 RPM",
      "par": "8,8 Nm (0,9 kgf-m o 6,5 ft.lbs) @ 5500 RPM",
      "velocidad_máxima": "83,0 km/h (51,6 mph)",
      "compresión": "10.0:1",
      "diámetro_carrera": "47,0 x 63,1 mm (1,9 x 2,5 pulgadas)",
      "sistema_combustible": "Inyección. PGM-FI",
      "refrigeración": "Aire",
      "caja de cambios": "Automática",
      "transmisión": "Correa (transmisión final)",
      "embrague": "CVT",
      "consumo_combustible": "1,79 litros/100 km (55,9 km/l o 131,41 mpg)",
      "emisiones": "41,5 CO2 g/km. (CO2 - Emisión de dióxido de carbono)",
      "bastidor": "chasis",
      "suspensión_delantera": "Horquilla telescópica",
      "rear_suspension": "Hidráulica con muelle ajustable en 3 pasos",
      "neumático_delantero": "90/90-12 ",
      "neumático_trasero": "90/100-10 ",
      "frenos_delanteros": "Freno de expansión (freno de tambor)",
      "frenos_traseros": "Freno expansible (freno de tambor)",
      "peso_total": "106,0 kg (233,7 libras)",
      "altura_asiento": "692 mm (27,2 pulgadas) Si es ajustable, la posición más baja",
      "altura_total": "1156 mm (45,5 pulgadas)",
      "longitud_total": "1833 mm (72,2 pulgadas)",
      "total_width": "697 mm (27.4 inches)",
      "distancia_al suelo": "162 mm (6,4 pulgadas)",
      "distancia entre ejes": "1260 mm (49,6 pulgadas)",
      "capacidad_combustible": "5,30 litros (1,40 galones US)",
      "arranque": "Eléctrico y patada"
    },
    {
      "marca": "Honda",
      "modelo": "Activa 125",
      "año": "2022",
      "tipo": "Scooter",
      "cilindrada": "123,7 ccm (7,55 pulgadas cúbicas)",
      "motor": "monocilíndrico, cuatro tiempos",
      "potencia": "8,2 CV (6,0 kW)) @ 6500 RPM",
      "par": "10,3 Nm (1,1 kgf-m o 7,6 ft.lbs) @ 5000 RPM",
      "compresión": "10.0:1",
      "diámetro_carrera": "50,0 x 63,1 mm (2,0 x 2,5 pulgadas)",
      "sistema_combustible": "Inyección. PGM-FI",
      "caja de cambios": "Automática",
      "transmisión": "Correa (transmisión final)",
      "bastidor": "chasis",
      "suspensión_delantera": "Horquilla telescópica",
      "suspensión_trasera": "Hidráulica con muelle ajustable en 3 pasos",
      "neumático_delantero": "90/90-12 ",
      "neumático_trasero": "90/100-10 ",
      "frenos_delanteros": "Single disc",
      "rear_brakes": "Freno de expansión (freno de tambor)",
      "peso_total": "109,0 kg (240,3 libras)",
      "altura_asiento": "712 mm (28,0 pulgadas) Si es ajustable, la posición más baja",
      "altura_total": "1170 mm (46,1 pulgadas)",
      "longitud_total": "1850 mm (72,8 pulgadas)",
      "total_width": "707 mm (27,8 pulgadas)",
      "distancia entre ejes": "1260 mm (49,6 pulgadas)",
      "capacidad_combustible": "5,30 litros (1,40 galones US)",
      "arranque": "Eléctrico y patada"
    },
    {
      "marca": "Honda",
      "modelo": "Africa Twin",
      "año": "2022",
      "tipo": "Enduro / offroad",
      "cilindrada": "1084,0 ccm (66,15 pulgadas cúbicas)",
      "motor": "bicilíndrico, cuatro tiempos",
      "potencia": "101,0 CV (73,7 kW)) @ 7500 RPM",
      "par": "105,0 Nm (10,7 kgf-m o 77,4 ft.lbs) @ 6250 RPM",
      "compresión": "10.1:1",
      "diámetro_carrera": "92,0 x 81,5 mm (3,6 x 3,2 pulgadas)",
      "válvulas_por_cilindro": "4",
      "sistema_combustible": "Inyección. Inyección electrónica de combustible PGM-FI (acelerador por cable)",
      "control_combustible": "Levas en cabeza simples (SOHC)",
      "ignición": "Encendido transistorizado completo",
      "refrigeración": "Líquido",
      "caja de cambios": "6 velocidades",
      "transmisión": "Cadena (transmisión final)",
      "embrague": "Doble embrague. Húmedo, multidisco con muelles helicoidales, asistencia de levas de aluminio y deslizante",
      "consumo_combustible": "4,90 litros/100 km (20,4 km/l o 48,00 mpg)",
      "emission": "113,7 g/km de CO2 (CO2 - Emisión de dióxido de carbono) ",
      "bastidor": "Tipo semidoble cuna de acero con subchasis trasero de acero de alta resistencia a la tracción",
      "suspensión delantera": "Horquilla telescópica invertida Showa de 45 mm tipo cartucho con regulador de precarga tipo dial y ajustes DF",
      "recorrido_rueda_delantera": "230 mm (9,1 pulgadas)",
      "suspensión_trasera": "Basculante monobloque de aluminio con Pro-Link con amortiguador SHOWA con carga de gas, regulador hidráulico de precarga tipo dial y ajustes de amortiguación de rebote",
      "recorrido_rueda_trasera": "220 mm (8,7 pulgadas)",
      "neumático_delantero": "90/90-21 ",
      "neumático_trasero": "150/70-R18 ",
      "frenos_delanteros": "Doble disco. ABS conmutable. Pinzas de 4 pistones y pastillas de metal sinterizado",
      "frenos_traseros": "Disco simple. ABS conmutable. Pinza de 2 pistones y pastillas de metal sinterizado",
      "peso_total": "238,0 kg (524,7 libras)",
      "altura_asiento": "851 mm (33,5 pulgadas) Si es ajustable, la posición más baja",
      "altura_total": "1395 mm (54,9 pulgadas)",
      "longitud_total": "2330 mm (91,7 pulgadas)",
      "total_width": "960 mm (37.8 inches)",
      "distancia_al suelo": "250 mm (9,8 pulgadas)",
      "distancia entre ejes": "1575 mm (62,0 pulgadas)",
      "capacidad_combustible": "24,80 litros (6,55 galones US)",
      "arranque": "Eléctrico"
    },
    {
      "marca": "Honda",
      "modelo": "Africa Twin Adventure Sports",
      "año": "2022",
      "tipo": "Enduro / offroad",
      "cilindrada": "1084,0 ccm (66,15 pulgadas cúbicas)",
      "motor": "bicilíndrico, cuatro tiempos",
      "potencia": "101,0 CV (73,7 kW)) @ 7500 RPM",
      "par": "105,0 Nm (10,7 kgf-m o 77,4 ft.lbs) @ 6250 RPM",
      "compresión": "10.1:1",
      "diámetro_carrera": "92,0 x 81,5 mm (3,6 x 3,2 pulgadas)",
      "válvulas_por_cilindro": "4",
      "sistema_combustible": "Inyección. Inyección electrónica de combustible PGM-FI (acelerador por cable)",
      "control_combustible": "Levas en cabeza simples (SOHC)",
      "ignición": "Encendido transistorizado completo",
      "refrigeración": "Líquido",
      "caja de cambios": "6 velocidades",
      "transmisión": "Cadena (transmisión final)",
      "embrague": "Húmedo, multidisco con muelles helicoidales, asistencia de levas de aluminio y embrague deslizante",
      "bastidor": "Tipo semidoble cuna de acero con subchasis trasero de acero de alta resistencia a la tracción",
      "suspensión delantera": "Horquilla telescópica invertida Showa de 45 mm tipo cartucho con regulador de precarga tipo dial y ajuste de amortiguación",
      "recorrido_rueda_delantera": "230 mm (9,1 pulgadas)",
      "suspensión_trasera": "Basculante monobloque de aluminio con Pro-Link con amortiguador Showa con carga de gas, ajuste hidráulico de precarga tipo dial y amortiguación de rebote",
      "recorrido_rueda_trasera": "220 mm (8,7 pulgadas)",
      "neumático_delantero": "90/90-21 ",
      "neumático_trasero": "150/70-R18 ",
      "frenos_delanteros": "Doble disco. ABS conmutable. Pinzas de 4 pistones y pastillas de metal sinterizado",
      "frenos_traseros": "Disco simple. ABS conmutable. Pinza de 2 pistones y pastillas de metal sinterizado",
      "peso_total": "238,0 kg (524,7 libras)",
      "altura_asiento": "850 mm (33,5 pulgadas) Si es ajustable, el ajuste más bajo",
      "altura_total": "1490 mm (58,7 pulgadas)",
      "longitud_total": "2330 mm (91,7 pulgadas)",
      "total_width": "960 mm (37.8 inches)",
      "distancia_al suelo": "250 mm (9,8 pulgadas)",
      "distancia entre ejes": "1575 mm (62,0 pulgadas)",
      "capacidad_combustible": "24,80 litros (6,55 galones US)",
      "arranque": "Eléctrico"
    },
    {
      "marca": "Honda",
      "modelo": "AirBlade 150",
      "año": "2022",
      "tipo": "Scooter",
      "cilindrada": "150,0 ccm (9,15 pulgadas cúbicas)",
      "motor": "monocilíndrico, cuatro tiempos",
      "sistema_combustible": "Inyección PGM-FI",
      "control_combustible": "Mono árbol de levas en cabeza (SOHC)",
      "refrigeración": "Líquido",
      "caja de cambios": "Automática",
      "transmisión": "Correa (transmisión final)",
      "suspensión_delantera": "Horquilla telescópica",
      "suspensión_trasera": "Monoamortiguador",
      "neumático_delantero": "90/80-14 ",
      "neumático_trasero": "100/80-14 ",
      "frenos_delanteros": "Disco simple. ABS",
      "rear_brakes": "Freno expansible (freno de tambor)",
      "peso_total": "113,0 kg (249,1 libras)",
      "seat_height": "773 mm (30,4 pulgadas) Si es ajustable, la posición más baja",
      "altura_total": "1112 mm (43,8 pulgadas)",
      "longitud_total": "1870 mm (73,6 pulgadas)",
      "total_width": "686 mm (27.0 inches)",
      "distancia_al suelo": "139 mm (5,5 pulgadas)",
      "fuel_capacity": "5,50 litros (1,45 galones US)",
      "arranque": "Eléctrico"
    },
    {
      "marca": "Honda",
      "model": "BeAT Street",
      "año": "2022",
      "tipo": "Scooter",
      "cilindrada": "108,0 ccm (6,59 pulgadas cúbicas)",
      "motor": "monocilíndrico, cuatro tiempos",
      "sistema_combustible": "Inyección PGM-FI",
      "control_combustible": "Mono árbol de levas en cabeza (SOHC)",
      "refrigeración": "Aire",
      "caja de cambios": "Automática",
      "transmisión": "Correa (transmisión final)",
      "consumo_combustible": "1,57 litros/100 km (63,7 km/l o 149,82 mpg)",
      "emisiones": "36,4 CO2 g/km. (CO2 - Emisión de dióxido de carbono) ",
      "suspensión_delantera": "horquilla telescópica",
      "rear_suspension": "Monoamortiguador",
      "neumático_delantero": "80/90-14 ",
      "neumático_trasero": "90/90-14 ",
      "frenos_delanteros": "Single disc",
      "rear_brakes": "Freno de expansión (freno de tambor)",
      "peso_total": "93,0 kg (205,0 libras)",
      "altura_asiento": "740 mm (29,1 pulgadas) Si es ajustable, la posición más baja",
      "altura_total": "1068 mm (42,0 pulgadas)",
      "longitud_total": "1856 mm (73,1 pulgadas)",
      "total_width": "667 mm (26.3 inches)",
      "distancia_al suelo": "146 mm (5,7 pulgadas)",
      "fuel_capacity": "4.00 litros (1.06 galones US)",
      "arranque": "Eléctrico y patada"
    },
    {
      "make": "Honda",
      "model": "Benly",
      "year": "2022",
      "type": "Scooter",
      "displacement": "108.0 ccm (6.59 cubic inches)",
      "engine": "Single cylinder, four-stroke",
      "power": "7.8 HP (5.7  kW)) @ 7000 RPM",
      "torque": "8.6 Nm (0.9 kgf-m or 6.3 ft.lbs) @ 5000 RPM",
      "compression": "9.5:1",
      "bore_stroke": "50.0 x 55.0 mm (2.0 x 2.2 inches)",
      "valves_per_cylinder": "2",
      "fuel_system": "Injection. PGM-FI",
      "fuel_control": "Overhead Cams (OHC)",
      "cooling": "Air",
      "gearbox": "Automatic",
      "transmission": "Belt   (final drive)",
      "clutch": "Dry multi-plate shoe",
      "fuel_consumption": "1.89 litres/100 km (52.9 km/l or 124.46 mpg)",
      "emission": "43.8 CO2 g/km. (CO2 - Carbon dioxide emission) ",
      "frame": "Underbone",
      "front_suspension": "Telescopic fork",
      "front_wheel_travel": "81 mm (3.2 inches)",
      "rear_suspension": "Unit swing type",
      "rear_wheel_travel": "73 mm (2.9 inches)",
      "front_tire": "90/90-12 ",
      "rear_tire": "110/80-10 ",
      "front_brakes": "Expanding brake (drum brake)",
      "rear_brakes": "Expanding brake (drum brake)",
      "dry_weight": "116.0 kg (255.7 pounds)",
      "seat_height": "710 mm (28.0 inches) If adjustable, lowest setting.",
      "total_height": "1040 mm (40.9 inches)",
      "total_length": "1815 mm (71.5 inches)",
      "total_width": "680 mm (26.8 inches)",
      "ground_clearance": "115 mm (4.5 inches)",
      "wheelbase": "1280 mm (50.4 inches)",
      "fuel_capacity": "10.00 litres (2.64 US gallons)",
      "starter": "Electric"
    },
    {
      "make": "Honda",
      "model": "CB1000R",
      "year": "2022",
      "type": "Naked bike",
      "displacement": "998.0 ccm (60.90 cubic inches)",
      "engine": "In-line four, four-stroke",
      "power": "143.5 HP (104.7  kW)) @ 10500 RPM",
      "torque": "104.0 Nm (10.6 kgf-m or 76.7 ft.lbs) @ 8250 RPM",
      "compression": "11.6:1",
      "bore_stroke": "76.0 x 56.5 mm (3.0 x 2.2 inches)",
      "valves_per_cylinder": "4",
      "fuel_system": "Injection. PGM-FI Fuel injection with automatic enrichment circuit and 36mm throttle bodies",
      "fuel_control": "Double Overhead Cams/Twin Cam (DOHC)",
      "ignition": "Computer-controlled digital transistorized with 3-D mapping",
      "cooling": "Liquid",
      "gearbox": "6-speed",
      "transmission": "Chain   (final drive)",
      "clutch": "Wet multiplate",
      "fuel_consumption": "6.02 litres/100 km (16.6 km/l or 39.07 mpg)",
      "emission": "139.7 CO2 g/km. (CO2 - Carbon dioxide emission) ",
      "frame": "Steel mono backbone",
      "front_suspension": "Showa SFF-BP USD fork",
      "front_wheel_travel": "120 mm (4.7 inches)",
      "rear_suspension": "Monoshock with gas-charged HMAS damper featuring 10-step pre-load and stepless rebound damping adjustment",
      "rear_wheel_travel": "131 mm (5.2 inches)",
      "front_tire": "120/70-ZR17 ",
      "rear_tire": "190/55-ZR17 ",
      "front_brakes": "Double disc. ABS. Floating discs. Four-piston calipers. Radially mounted. ",
      "rear_brakes": "Single disc. ABS. Single-piston caliper. ",
      "total_weight": "211.0 kg (465.2 pounds)",
      "seat_height": "830 mm (32.7 inches) If adjustable, lowest setting.",
      "total_height": "1090 mm (42.9 inches)",
      "total_length": "2121 mm (83.5 inches)",
      "total_width": "790 mm (31.1 inches)",
      "ground_clearance": "131 mm (5.2 inches)",
      "wheelbase": "1455 mm (57.3 inches)",
      "fuel_capacity": "16.20 litres (4.28 US gallons)",
      "starter": "Electric"
    },
    {
      "marca": "Honda",
      "modelo": "CB1000R Black Edition",
      "año": "2022",
      "tipo": "moto desnuda",
      "cilindrada": "998,0 ccm (60,90 pulgadas cúbicas)",
      "motor": "cuatro en línea, cuatro tiempos",
      "potencia": "143,5 CV (104,7 kW)) @ 10500 RPM",
      "par": "104,0 Nm (10,6 kgf-m o 76,7 ft.lbs) @ 8250 RPM",
      "compresión": "11.6:1",
      "diámetro_carrera": "75,0 x 56,5 mm (3,0 x 2,2 pulgadas)",
      "válvulas_por_cilindro": "4",
      "sistema_combustible": "Inyección Inyección de combustible PGM-FI con circuito de enriquecimiento automático y cuerpos de mariposa de 36 mm",
      "fuel_control": "Doble árbol de levas en cabeza/doble árbol de levas (DOHC)",
      "ignición": "Transistorizado digital controlado por ordenador con mapeado 3D",
      "refrigeración": "Líquido",
      "caja de cambios": "6 velocidades",
      "transmisión": "Cadena (transmisión final)",
      "embrague": "multidisco húmedo",
      "consumo_de_combustible": "5,80 litros/100 km (17,2 km/l o 40,56 mpg)",
      "emisiones": "134,6 CO2 g/km. (CO2 - Emisión de dióxido de carbono) ",
      "bastidor": "Monocasco de acero",
      "suspensión_delantera": "Horquilla Showa SFF-BP de 43 mm con ajuste de precarga de muelle, amortiguación de rebote y compresión",
      "recorrido_rueda_delantera": "120 mm (4,7 pulgadas)",
      "suspensión_trasera": "Amortiguador Showa simple con ajuste de precarga de muelle y amortiguación de rebote",
      "recorrido_rueda_trasera": "131 mm (5,2 pulgadas)",
      "neumático_delantero": "120/70-17 ",
      "neumático_trasero": "190/55-17 ",
      "frenos_delanteros": "Doble disco. Discos flotantes. Pinzas de cuatro pistones. Montaje radial. ABS. ",
      "frenos_traseros": "Disco simple. Pinza de un pistón. ABS",
      "peso_total": "211,8 kg (467,0 libras)",
      "altura_asiento": "830 mm (32,7 pulgadas) Si es ajustable, la posición más baja",
      "altura_total": "1090 mm (42,9 pulgadas)",
      "longitud_total": "2120 mm (83,5 pulgadas)",
      "total_width": "789 mm (31.1 inches)",
      "distancia_al suelo": "131 mm (5,2 pulgadas)",
      "capacidad_combustible": "16,20 litros (4,28 galones US)",
      "arranque": "Eléctrico"
    },
    {
      "marca": "Honda",
      "modelo": "CB125F",
      "año": "2022",
      "tipo": "Allround",
      "cilindrada": "123,9 ccm (7,56 pulgadas cúbicas)",
      "motor": "monocilíndrico, cuatro tiempos",
      "potencia": "10,7 CV (7,8 kW)) @ 7500 RPM",
      "par": "10,9 Nm (1,1 kgf-m u 8,0 ft.lbs) @ 6000 RPM",
      "compresión": "10.0:1",
      "diámetro_carrera": "50,0 x 63,1 mm (2,0 x 2,5 pulgadas)",
      "válvulas_por_cilindro": "2",
      "sistema_combustible": "Inyección PGM-FI",
      "control_combustible": "Levas en cabeza (OHC)",
      "refrigeración": "Aire",
      "caja de cambios": "5 velocidades",
      "transmisión": "Cadena (transmisión final)",
      "embrague": "Húmedo, multidisco con muelles helicoidales",
      "consumo_de_combustible": "1,48 litros/100 km (67,6 km/l o 158,93 mpg)",
      "emission": "34,3 g/km de CO2 (CO2 - Emisión de dióxido de carbono)",
      "bastidor": "Acero tubular",
      "suspensión_delantera": "Horquilla telescópica, 31 mm",
      "suspensión_trasera": "Basculante doble, 5 etapas prload",
      "neumático_delantero": "80/100-18 ",
      "neumático_trasero": "90/90-18 ",
      "frenos_delanteros": "Disco simple. Pinzas de dos pistones. ",
      "frenos_traseros": "Freno de expansión (freno de tambor)",
      "peso_total": "117,0 kg (257,9 libras)",
      "seat_height": "790 mm (31,1 pulgadas) Si es ajustable, la posición más baja",
      "altura_total": "1100 mm (43,3 pulgadas)",
      "longitud_total": "2015 mm (79.3 inches)",
      "total_width": "750 mm (29.5 inches)",
      "distancia_al suelo": "160 mm (6.3 inches)",
      "distancia entre ejes": "1286 mm (50,6 pulgadas)",
      "capacidad_combustible": "11.00 litros (2.91 galones US)",
      "arranque": "Eléctrico"
    },
    {
      "marca": "Honda",
      "modelo": "CB125R",
      "año": "2022",
      "tipo": "Naked bike",
      "cilindrada": "124,9 ccm (7,62 pulgadas cúbicas)",
      "motor": "monocilíndrico, cuatro tiempos",
      "potencia": "14,8 CV (10,8 kW)) @ 10000 RPM",
      "par": "11,6 Nm (1,2 kgf-m u 8,6 ft.lbs) @ 8000 RPM",
      "velocidad_máxima": "105,0 km/h (65,2 mph)",
      "compresión": "11.3:1",
      "carrera_calibre": "57,3 x 48,4 mm (2,3 x 1,9 pulgadas)",
      "sistema_combustible": "Inyección PGM-FI ",
      "control_combustible": "Doble árbol de levas en cabeza/doble árbol de levas (DOHC)",
      "refrigeración": "Líquido",
      "caja de cambios": "6 velocidades",
      "transmisión": "Cadena (transmisión final)",
      "embrague": "Húmedo, multidisco con muelles helicoidales",
      "consumo_de_combustible": "2,13 litros/100 km (46,9 km/l o 110,43 mpg)",
      "emission": "49,4 g/km de CO2 (CO2 - Emisión de dióxido de carbono)",
      "bastidor": "Diamante de pivote interior de acero",
      "suspensión_delantera": "Horquilla telescópica USD, 41mm",
      "recorrido_rueda_delantera": "120 mm (4,7 pulgadas)",
      "suspensión_trasera": "Monoamortiguador",
      "recorrido_rueda_trasera": "126 mm (5,0 pulgadas)",
      "neumático_delantero": "100/70-R17 ",
      "neumático_trasero": "150/60-R17 ",
      "frenos_delanteros": "Disco simple. Pinzas de 4 pistones. ",
      "frenos_traseros": "Single disc",
      "peso_total": "130,0 kg (286,6 libras)",
      "seat_height": "816 mm (32,1 pulgadas) Si es ajustable, la posición más baja",
      "longitud_total": "2018 mm (79,4 pulgadas)",
      "ground_clearance": "140 mm (5,5 pulgadas)",
      "distancia entre ejes": "1345 mm (53,0 pulgadas)",
      "capacidad_combustible": "10,10 litros (2,67 galones US)",
      "arranque": "Eléctrico"
    },
    {
      "marca": "Honda",
      "modelo": "CB125e",
      "año": "2022",
      "tipo": "Naked bike",
      "cilindrada": "124,0 ccm (7,57 pulgadas cúbicas)",
      "motor": "Monocilíndrico, cuatro tiempos",
      "velocidad_máxima": "105,0 km/h (65,2 mph)",
      "compresión": "9.0:1",
      "diámetro_carrera": "56,5 x 49,5 mm (2,2 x 1,9 pulgadas)",
      "válvulas_por_cilindro": "2",
      "sistema_combustible": "carburador",
      "refrigeración": "Aire",
      "caja de cambios": "5 velocidades",
      "transmisión": "Cadena (transmisión final)",
      "consumo_combustible": "2,13 litros/100 km (46,9 km/l o 110,43 mpg)",
      "emisiones": "49,4 CO2 g/km. (CO2 - Emisión de dióxido de carbono) ",
      "suspensión_delantera": "horquilla telescópica",
      "recorrido_rueda_delantera": "118 mm (4,6 pulgadas)",
      "suspensión_trasera": "Amortiguadores dobles",
      "recorrido_rueda_trasera": "70 mm (2,8 pulgadas)",
      "neumático_delantero": "90/100-18 ",
      "neumático_trasero": "90/90-18 ",
      "frenos_delanteros": "Disco simple. . ",
      "rear_brakes": "Freno de expansión (freno de tambor)",
      "peso_total": "137,0 kg (302,0 libras)",
      "seat_height": "767 mm (30,2 pulgadas) Si es ajustable, la posición más baja",
      "altura_total": "1094 mm (43,1 pulgadas)",
      "longitud_total": "2026 mm (79,8 pulgadas)",
      "total_width": "765 mm (30.1 inches)",
      "distancia_al suelo": "145 mm (5,7 pulgadas)",
      "distancia entre ejes": "1286 mm (50,6 pulgadas)",
      "capacidad_combustible": "14.00 litros (3.70 galones US)",
      "arranque": "Eléctrico"
    },
    {
      "marca": "Honda",
      "modelo": "CB150F",
      "año": "2022",
      "tipo": "Allround",
      "cilindrada": "149,2 ccm (9,10 pulgadas cúbicas)",
      "motor": "monocilíndrico, cuatro tiempos",
      "compresión": "10.0:1",
      "diámetro_carrera": "9,1 x 57,8 mm (0,4 x 2,3 pulgadas)",
      "válvulas_por_cilindro": "2",
      "control_combustible": "levas en cabeza (OHC)",
      "refrigeración": "Aire",
      "caja de cambios": "5 velocidades",
      "transmisión": "Cadena (transmisión final)",
      "embrague": "húmedo, multidisco con muelles helicoidales",
      "bastidor": "Acero tubular",
      "suspensión_delantera": "Horquilla telescópica",
      "recorrido_rueda_delantera": "107 mm (4,2 pulgadas)",
      "suspensión_trasera": "Doble amortiguador, basculante",
      "recorrido_rueda_trasera": "91 mm (3,6 pulgadas)",
      "neumático_delantero": "80/100-18 ",
      "neumático_trasero": "90/90-18 ",
      "frenos_delanteros": "Disco simple. Pinzas de dos pistones. ",
      "frenos_traseros": "Freno de expansión (freno de tambor)",
      "peso_total": "124,0 kg (273,4 libras)",
      "seat_height": "766 mm (30,2 pulgadas) Si es ajustable, la posición más baja",
      "altura_total": "1085 mm (42,7 pulgadas)",
      "longitud_total": "2051 mm (80,7 pulgadas)",
      "total_width": "760 mm (29.9 inches)",
      "distancia_al suelo": "168 mm (6.6 inches)",
      "distancia entre ejes": "1311 mm (51,6 pulgadas)",
      "capacidad_combustible": "13.00 litros (3.43 galones US)",
      "arranque": "Eléctrico"
    },
    {
      "marca": "Honda",
      "modelo": "CB200X",
      "año": "2022",
      "tipo": "Sport",
      "cilindrada": "184,0 ccm (11,23 pulgadas cúbicas)",
      "motor": "monocilíndrico, cuatro tiempos",
      "potencia": "17,0 CV (12,4 kW)) @ 8500 RPM",
      "par": "16,1 Nm (1,6 kgf-m o 11,9 ft.lbs) @ 6000 RPM",
      "compresión": "9.5:1",
      "diámetro_carrera": "61,0 x 63,0 mm (2,4 x 2,5 pulgadas)",
      "sistema_combustible": "Inyección. PGM-FI",
      "caja de cambios": "5 velocidades",
      "transmisión": "Cadena (transmisión final)",
      "embrague": "multidisco húmedo",
      "bastidor": "Diamante",
      "suspensión delantera": "Horquilla invertida",
      "suspensión_trasera": "Monoshock ",
      "front_tire": "110/70-17 ",
      "neumático_trasero": "140/70-17 ",
      "frenos_delanteros": "Disco simple. ABS",
      "frenos_traseros": "Disco simple. ABS",
      "peso_total": "147,0 kg (324,1 libras)",
      "seat_height": "810 mm (31,9 pulgadas) Si es ajustable, la posición más baja",
      "altura_total": "1248 mm (49,1 pulgadas)",
      "longitud_total": "2035 mm (80.1 inches)",
      "ancho_total": "843 mm (33.2 inches)",
      "distancia_al suelo": "167 mm (6,6 pulgadas)",
      "distancia entre ejes": "1386 mm (54,6 pulgadas)",
      "capacidad_combustible": "12.00 litros (3.17 galones US)",
      "arranque": "Eléctrico y patada"
    },
    {
      "marca": "Honda",
      "modelo": "CB300R",
      "año": "2022",
      "tipo": "moto desnuda",
      "cilindrada": "286,0 ccm (17,45 pulgadas cúbicas)",
      "motor": "monocilíndrico, cuatro tiempos",
      "potencia": "34,9 CV (25,5 kW)) @ 10500 RPM",
      "par": "22,9 Nm (2,3 kgf-m o 16,9 ft.lbs)",
      "compresión": "10.7:1",
      "diámetro_carrera": "76,0 x 63,0 mm (3,0 x 2,5 pulgadas)",
      "válvulas_por_cilindro": "4",
      "sistema_combustible": "Inyección. Inyección de combustible con cuerpo de mariposa de 38 mm",
      "fuel_control": "Doble árbol de levas en cabeza/doble árbol de levas (DOHC)",
      "ignición": "Completamente transistorizado",
      "refrigeración": "Líquido",
      "caja de cambios": "6 velocidades",
      "transmisión": "Cadena (transmisión final)",
      "embrague": "Multidisco húmedo con muelles helicoidales",
      "consumo_de_combustible": "3,31 litros/100 km (30,2 km/l o 71,06 mpg)",
      "emission": "76,8 g/km de CO2 (CO2 - Emisión de dióxido de carbono)",
      "bastidor": "Tubo de acero",
      "suspensión_delantera": "Horquilla telescópica de 41 mm",
      "recorrido_rueda_delantera": "118 mm (4,7 pulgadas)",
      "suspensión_trasera": "monoamortiguador Pro-Link con cinco posiciones de ajuste de la precarga del muelle",
      "recorrido_rueda_trasera": "132 mm (5,2 pulgadas)",
      "neumático_delantero": "110/70-17 ",
      "neumático_trasero": "150/60-17 ",
      "frenos_delanteros": "Disco simple. ABS",
      "frenos_traseros": "Disco simple. ABS",
      "peso_total": "143,8 kg (317,0 libras)",
      "seat_height": "800 mm (31,5 pulgadas) Si es ajustable, el ajuste más bajo",
      "distancia entre ejes": "1354 mm (53,3 pulgadas)",
      "capacidad_combustible": "10,22 litros (2,70 galones US)",
      "arranque": "Eléctrico"
    },
    {
      "marca": "Honda",
      "model": "CB300R Neo Sports Cafe",
      "año": "2022",
      "tipo": "Naked bike",
      "cilindrada": "286,0 ccm (17,45 pulgadas cúbicas)",
      "motor": "monocilíndrico, cuatro tiempos",
      "potencia": "38,9 CV (28,4 kW)) @ 9000 RPM",
      "par": "27,5 Nm (2,8 kgf-m o 20,3 ft.lbs) @ 7750 RPM",
      "compresión": "10.7:1",
      "diámetro_carrera": "76,0 x 63,0 mm (3,0 x 2,5 pulgadas)",
      "válvulas_por_cilindro": "4",
      "sistema_combustible": "Inyección. Inyección de combustible con cuerpo de mariposa de 38 mm",
      "fuel_control": "Doble árbol de levas en cabeza/doble árbol de levas (DOHC)",
      "ignition": "Transistorizado digital controlado por ordenador con avance electrónico",
      "refrigeración": "Líquido",
      "caja de cambios": "6 velocidades",
      "transmisión": "Cadena (transmisión final)",
      "embrague": "multidisco húmedo, ssist/slipper",
      "consumo_combustible": "3,31 litros/100 km (30,2 km/l o 71,06 mpg)",
      "emission": "76,8 CO2 g/km. (CO2 - Emisión de dióxido de carbono) ",
      "bastidor": "diamante de acero",
      "suspensión_delantera": "Horquilla delantera Showa Separate Function Big Piston (SFF-BP) USD de 41 mm",
      "recorrido_rueda_delantera": "130 mm (5,1 pulgadas)",
      "suspensión_trasera": "Amortiguador monoamortiguador con precarga ajustable en 5 etapas",
      "recorrido_rueda_trasera": "107 mm (4,2 pulgadas)",
      "neumático_delantero": "110/70-R17 ",
      "neumático_trasero": "150/60-R17 ",
      "frenos_delanteros": "Disco simple. ABS. Disco flotante con pinza Nissin de 4 pistones de anclaje radial",
      "frenos_traseros": "Disco simple. ABS",
      "peso_total": "144,0 kg (317,5 libras)",
      "seat_height": "899 mm (35,4 pulgadas) Si es ajustable, la posición más baja",
      "altura_total": "1052 mm (41,4 pulgadas)",
      "longitud_total": "2012 mm (79,2 pulgadas)",
      "ancho_total": "802 mm (31,6 pulgadas)",
      "distancia entre ejes": "1354 mm (53,3 pulgadas)",
      "capacidad_combustible": "10,22 litros (2,70 galones US)",
      "arranque": "Eléctrico"
    },
    {
      "marca": "Honda",
      "modelo": "CB350RS",
      "año": "2022",
      "tipo": "Sport",
      "cilindrada": "348,0 ccm (21,23 pulgadas cúbicas)",
      "motor": "monocilíndrico, cuatro tiempos",
      "potencia": "20,8 CV (15,2 kW)) @ 5500 RPM",
      "par": "30,0 Nm (3,1 kgf-m o 22,1 ft.lbs) @ 3000 RPM",
      "compresión": "9.5:1",
      "diámetro_carrera": "70,0 x 90,5 mm (2,8 x 3,6 pulgadas)",
      "sistema_combustible": "Inyección. PGM-FI",
      "caja de cambios": "5 velocidades",
      "transmisión": "Cadena (transmisión final)",
      "embrague": "multidisco húmedo",
      "bastidor": "Media cuna dúplex",
      "suspensión_delantera": "Horquilla telescópica",
      "suspensión_trasera": "Twin shocks",
      "front_tire": "100/90-19 ",
      "neumático_trasero": "150/70-17 ",
      "frenos_delanteros": "Disco simple. ABS",
      "frenos_traseros": "Disco simple. ABS",
      "peso_total": "179,0 kg (394,6 libras)",
      "seat_height": "800 mm (31,5 pulgadas) Si es ajustable, el ajuste más bajo",
      "altura_total": "1097 mm (43,2 pulgadas)",
      "longitud_total": "2171 mm (85.5 inches)",
      "total_width": "804 mm (31.7 inches)",
      "distancia_al suelo": "168 mm (6,6 pulgadas)",
      "distancia entre ejes": "1386 mm (54,6 pulgadas)",
      "capacidad_combustible": "15.00 litros (3.96 galones US)",
      "arranque": "Eléctrico"
    },
    {
      "marca": "Honda",
      "modelo": "CB500F",
      "año": "2022",
      "tipo": "moto desnuda",
      "cilindrada": "471,0 ccm (28,74 pulgadas cúbicas)",
      "motor": "bicilíndrico, cuatro tiempos",
      "potencia": "46,9 CV (34,3 kW)) @ 8600 RPM",
      "par": "43,0 Nm (4,4 kgf-m o 31,7 ft.lbs) @ 6500 RPM",
      "compresión": "10.7:1",
      "diámetro_carrera": "67,0 x 66,8 mm (2,6 x 2,6 pulgadas)",
      "válvulas_por_cilindro": "4",
      "sistema_combustible": "Inyección PGM-FI con cuerpos de mariposa de 34 mm",
      "fuel_control": "Doble árbol de levas en cabeza/doble árbol de levas (DOHC)",
      "ignición": "Transistorizado digital controlado por ordenador con avance electrónico",
      "refrigeración": "Líquido",
      "caja de cambios": "6 velocidades",
      "transmisión": "Cadena (transmisión final)",
      "embrague": "Multidisco húmedo, embrague asistido/deslizante",
      "consumo_combustible": "3,50 litros/100 km (28,6 km/l o 67,21 mpg)",
      "emission": "81,2 g/km de CO2 (CO2 - Emisión de dióxido de carbono) ",
      "bastidor": "tubo de diamante",
      "suspensión_delantera": "Horquilla Showa 41mm SFF-BP USD, ajustable en precarga",
      "recorrido_rueda_delantera": "120 mm (4,7 pulgadas)",
      "suspensión_trasera": "Prolink mono con ajuste de precarga de 5 etapas, basculante transversal hueco de acero",
      "recorrido_rueda_trasera": "135 mm (5,3 pulgadas)",
      "neumático_delantero": "120/70-ZR17",
      "neumático_trasero": "160/60-ZR17 ",
      "frenos_delanteros": "Disco simple. ABS. Pinzas Nissin de dos pistones de anclaje radial",
      "frenos_traseros": "Monodisco. ABS. Disco ondulado. ",
      "peso_en_seco": "192,0 kg (423,3 libras)",
      "peso_total": "189.0 kg (416.7 pounds)",
      "altura_asiento": "790 mm (31,1 pulgadas) Si es ajustable, la posición más baja",
      "altura_total": "1060 mm (41,7 pulgadas)",
      "longitud_total": "2080 mm (81,9 pulgadas)",
      "anchura_total": "800 mm (31.5 inches)",
      "distancia_al suelo": "145 mm (5.7 inches)",
      "distancia entre ejes": "1410 mm (55,5 pulgadas)",
      "capacidad_combustible": "16,70 litros (4,41 galones US)",
      "arranque": "Eléctrico"
    },
    {
      "marca": "Honda",
      "modelo": "CB500X",
      "año": "2022",
      "tipo": "Sport",
      "cilindrada": "471,0 ccm (28,74 pulgadas cúbicas)",
      "motor": "bicilíndrico, cuatro tiempos",
      "potencia": "46,9 CV (34,3 kW)) @ 8600 RPM",
      "par": "43,0 Nm (4,4 kgf-m o 31,7 ft.lbs) @ 6500 RPM",
      "compresión": "10.7:1",
      "diámetro_carrera": "67,0 x 66,8 mm (2,6 x 2,6 pulgadas)",
      "válvulas_por_cilindro": "4",
      "sistema_combustible": "Inyección PGM-FI con cuerpos de mariposa de 34 mm",
      "fuel_control": "Doble árbol de levas en cabeza/doble árbol de levas (DOHC)",
      "ignición": "Transistorizado digital controlado por ordenador con avance electrónico",
      "refrigeración": "Líquido",
      "caja de cambios": "6 velocidades",
      "transmisión": "Cadena (transmisión final)",
      "embrague": "multidisco húmedo",
      "consumo_de_combustible": "3,60 litros/100 km (27,8 km/l o 65,34 mpg)",
      "emisiones": "83,5 CO2 g/km. (CO2 - Emisión de dióxido de carbono)",
      "chasis": "Diamante, acero",
      "suspensión delantera": "Horquilla Showa 41mm SFF-BP USD, ajustable en precarga",
      "recorrido_rueda_delantera": "150 mm (5,9 pulgadas)",
      "suspensión_trasera": "Prolink mono con ajuste de precarga de 5 etapas, basculante transversal hueco de acero",
      "recorrido_rueda_trasera": "135 mm (5,3 pulgadas)",
      "neumático_delantero": "110/80-19 ",
      "neumático_trasero": "160/60-17 ",
      "frenos_delanteros": "Doble disco. ABS. Disco ondulado. Pinzas de dos pistones. ",
      "frenos_traseros": "Disco simple. ABS. Disco ondulado. ",
      "peso_total": "199,0 kg (438,7 libras)",
      "altura_asiento": "830 mm (32,7 pulgadas) Si es ajustable, la posición más baja",
      "altura_total": "1358 mm (53,5 pulgadas)",
      "longitud_total": "2155 mm (84,8 pulgadas)",
      "total_width": "826 mm (32.5 inches)",
      "distancia_al suelo": "180 mm (7.1 inches)",
      "distancia entre ejes": "1445 mm (56,9 pulgadas)",
      "capacidad_combustible": "17,50 litros (4,62 galones US)",
      "arranque": "Eléctrico"
    },
    {
      "marca": "Honda",
      "modelo": "CB650R",
      "año": "2022",
      "tipo": "moto desnuda",
      "cilindrada": "649,0 ccm (39,60 pulgadas cúbicas)",
      "motor": "cuatro en línea, cuatro tiempos",
      "potencia": "93,9 CV (68,5 kW)) @ 12000 RPM",
      "par": "63,0 Nm (6,4 kgf-m o 46,5 ft.lbs) @ 9500 RPM",
      "compresión": "11.6:1",
      "diámetro_carrera": "67,0 x 46,0 mm (2,6 x 1,8 pulgadas)",
      "válvulas_por_cilindro": "4",
      "sistema_combustible": "Inyección PGM-FI",
      "control_combustible": "Doble árbol de levas en cabeza/doble árbol de levas (DOHC)",
      "ignición": "Transistorizado digital controlado por ordenador con avance electrónico",
      "refrigeración": "Líquido",
      "caja de cambios": "6 velocidades",
      "transmisión": "Cadena (transmisión final)",
      "embrague": "húmedo, multidisco con muelles helicoidales",
      "bastidor": "diamante de acero",
      "suspensión_delantera": "Horquilla delantera Showa Separate Function Big Piston (SFF-BP) USD de 41 mm",
      "suspensión_trasera": "Amortiguador Monoshock con precarga ajustable en 7 etapas,",
      "neumático_delantero": "120/70-17 ",
      "neumático_trasero": "180/55-17 ",
      "frenos_delanteros": "Doble disco. ABS. Pinzas radiales de cuatro pistones",
      "frenos_traseros": "Disco simple. ABS Pinza de un pistón. ",
      "peso_total": "202,5 kg (446,4 libras)",
      "altura_asiento": "810 mm (31,9 pulgadas) Si es ajustable, la posición más baja",
      "altura_total": "1075 mm (42,3 pulgadas)",
      "longitud_total": "2130 mm (83,9 pulgadas)",
      "ancho_total": "780 mm (30.7 inches)",
      "distancia_al suelo": "130 mm (5.1 inches)",
      "distancia entre ejes": "1450 mm (57,1 pulgadas)",
      "capacidad_combustible": "15,40 litros (4,07 galones US)",
      "arranque": "Eléctrico"
    },
    {
      "marca": "Honda",
      "modelo": "CBR1000RR-R Fireblade",
      "año": "2022",
      "tipo": "Sport",
      "cilindrada": "998,0 ccm (60,90 pulgadas cúbicas)",
      "motor": "cuatro en línea, cuatro tiempos",
      "potencia": "215,0 CV (156,9 kW)) @ 14500 RPM",
      "par": "112,0 Nm (11,4 kgf-m o 82,6 ft.lbs) @ 12500 RPM",
      "compresión": "13.4:1",
      "diámetro_carrera": "76,0 x 55,0 mm (3,0 x 2,2 pulgadas)",
      "válvulas_por_cilindro": "4",
      "sistema_combustible": "Inyección. Inyección de combustible de doble etapa programada (PGM-DSFI) con cuerpos de mariposa de 48 mm, inyectores Denso de 12 orificios",
      "fuel_control": "Doble árbol de levas en cabeza/doble árbol de levas (DOHC)",
      "encendido": "Digital transistorizado con avance electrónico",
      "refrigeración": "Líquido",
      "caja de cambios": "6 velocidades",
      "transmisión": "Cadena (transmisión final)",
      "embrague": "multidisco húmedo",
      "consumo_de_combustible": "6,19 litros/100 km (16,2 km/l o 38,00 mpg)",
      "emission": "143,6 CO2 g/km. (CO2 - Emisión de dióxido de carbono)",
      "bastidor": "Monocasco de acero",
      "suspensión_delantera": "Horquilla telescópica SHOWA BPF de 43 mm con ajuste de precarga, compresión y rebote",
      "recorrido_rueda_delantera": "120 mm (4,7 pulgadas)",
      "suspensión_trasera": "Basculante SHOWA BFRC-Lite Pro-Link con ajuste de precarga en 10 pasos, compresión continua y amortiguación de rebote",
      "recorrido_rueda_trasera": "137 mm (5,4 pulgadas)",
      "neumático_delantero": "120/70-ZR17",
      "neumático_trasero": "200/55-ZR17 ",
      "frenos_delanteros": "Doble disco. Discos flotantes. Pinzas de cuatro pistones. Montadas radialmente. ",
      "frenos_traseros": "Disco simple. Pinza de un pistón. ABS",
      "peso_total": "194,1 kg (428,0 libras)",
      "altura_asiento": "820 mm (32,3 pulgadas) Si es ajustable, el ajuste más bajo",
      "altura_total": "1120 mm (44,1 pulgadas)",
      "longitud_total": "2098 mm (82,6 pulgadas)",
      "total_width": "744 mm (29.3 inches)",
      "distancia_al suelo": "135 mm (5,3 pulgadas)",
      "distancia entre ejes": "1405 mm (55,3 pulgadas)",
      "capacidad_combustible": "16,10 litros (4,25 galones US)",
      "arranque": "Eléctrico"
    },
    {
      "marca": "Honda",
" modelo": "CBR1000RR-R Fireblade SP",
      "año": "2022",
      "tipo": "Sport",
      "cilindrada": "999.0 ccm (60.96 pulgadas cúbicas)",
      "motor": "cuatro en línea, cuatro tiempos",
      "potencia": "214,6 CV (156,6 kW)) @ 14500 RPM",
      "par": "112,0 Nm (11,4 kgf-m o 82,6 ft.lbs) @ 12500 RPM",
      "compresión": "13.4:1",
      "diámetro_carrera": "81,0 x 48,5 mm (3,2 x 1,9 pulgadas)",
      "válvulas_por_cilindro": "4",
      "sistema_combustible": "Inyección. Inyección de combustible de doble etapa programada (PGM-DSFI) con cuerpos de mariposa de 52 mm, inyectores Denso de 12 orificios",
      "fuel_control": "Doble árbol de levas en cabeza/doble árbol de levas (DOHC)",
      "encendido": "Electrónico, transistor digital",
      "refrigeración": "Líquido",
      "caja de cambios": "6 velocidades",
      "transmisión": "Cadena (transmisión final)",
      "embrague": "Embrague hidráulico multidisco húmedo",
      "consumo_combustible": "6,60 litros/100 km (15,2 km/l o 35,64 mpg)",
      "emission": "153,1 CO2 g/km. (CO2 - Emisión de dióxido de carbono)",
      "chasis": "Aluminium Twin Tube composite twin spark",
      "suspensión_delantera": "Horquilla delantera Öhlins NPX Smart-EC de 43 mm con ajustes de precarga, compresión y rebote controlados electrónicamente",
      "recorrido_rueda_delantera": "125 mm (4,9 pulgadas)",
      "suspensión_trasera": "Basculante Öhlins TTX36 S-EC Pro-Link con amortiguación de precarga, compresión y rebote",
      "recorrido_rueda_trasera": "143 mm (5,6 pulgadas)",
      "neumático_delantero": "120/70-ZR17",
      "neumático_trasero": "200/55-ZR17 ",
      "frenos_delanteros": "Doble disco. Discos flotantes. Pinzas de cuatro pistones. Montaje radial. ABS. ",
      "frenos_traseros": "Disco simple. Pinza de doble pistón. ABS",
      "peso_total": "201,3 kg (443,8 libras)",
      "altura_asiento": "828 mm (32,6 pulgadas) Si es ajustable, la posición más baja",
      "altura_total": "1140 mm (44,9 pulgadas)",
      "longitud_total": "2100 mm (82,7 pulgadas)",
      "total_width": "745 mm (29.3 inches)",
      "distancia_al suelo": "119 mm (4,7 pulgadas)",
      "distancia entre ejes": "1460 mm (57,5 pulgadas)",
      "capacidad_combustible": "16,28 litros (4,30 galones US)",
      "arranque": "Eléctrico"
    },
    {
      "marca": "Honda",
      "modelo": "CBR150R",
      "año": "2022",
      "tipo": "Sport",
      "cilindrada": "149.0 ccm (9.09 pulgadas cúbicas)",
      "motor": "Monocilíndrico, cuatro tiempos",
      "válvulas_por_cilindro": "4",
      "sistema_de_combustible": "Inyección PGM-FI",
      "control_combustible": "Doble árbol de levas en cabeza/doble árbol de levas (DOHC)",
      "refrigeración": "Líquido",
      "caja de cambios": "6 velocidades",
      "transmisión": "Cadena (transmisión final)",
      "embrague": "Embrague asistido y deslizante",
      "consumo_combustible": "2,41 litros/100 km (41,5 km/l o 97,60 mpg)",
      "emission": "55,9 g/km de CO2 (CO2 - Emisión de dióxido de carbono) ",
      "suspensión_delantera": "Horquilla telescópica invertida",
      "rear_suspension": "Amortiguadores dobles",
      "neumático_delantero": "100/80-17 ",
      "neumático_trasero": "130/70-17 ",
      "frenos_delanteros": "Single disc",
      "frenos_traseros": "Single disc",
      "peso_total": "137.0 kg (302.0 pounds)",
      "altura_asiento": "788 mm (31,0 pulgadas) Si es ajustable, la posición más baja",
      "altura_total": "1090 mm (42,9 pulgadas)",
      "longitud_total": "1983 mm (78,1 pulgadas)",
      "ancho_total": "700 mm (27,6 pulgadas)",
      "distancia_al suelo": "151 mm (5,9 pulgadas)",
      "capacidad_combustible": "12,00 litros (3,17 galones US)",
      "arranque": "Eléctrico"
    },
    {
      "marca": "Honda",
      "modelo": "CBR300R",
      "año": "2022",
      "tipo": "Sport",
      "cilindrada": "286,0 ccm (17,45 pulgadas cúbicas)",
      "motor": "monocilíndrico, cuatro tiempos",
      "potencia": "34,9 CV (25,5 kW)) @ 10500 RPM",
      "par": "22,9 Nm (2,3 kgf-m o 16,9 ft.lbs)",
      "compresión": "10.7:1",
      "diámetro_carrera": "76,0 x 63,0 mm (3,0 x 2,5 pulgadas)",
      "válvulas_por_cilindro": "4",
      "sistema_combustible": "Inyección PGM-Fi, cuerpo de mariposa de 38 mm",
      "fuel_control": "Doble árbol de levas en cabeza/doble árbol de levas (DOHC)",
      "ignición": "Transistorizado digital controlado por ordenador con avance electrónico",
      "refrigeración": "Líquido",
      "caja de cambios": "6 velocidades",
      "transmisión": "Cadena (transmisión final)",
      "embrague": "Multidisco húmedo con muelles helicoidales",
      "consumo_de_combustible": "3,31 litros/100 km (30,2 km/l o 71,06 mpg)",
      "emission": "76,8 g/km de CO2 (CO2 - Emisión de dióxido de carbono)",
      "bastidor": "Tubo de acero",
      "suspensión_delantera": "Horquilla de 37 mm",
      "recorrido_rueda_delantera": "118 mm (4,7 pulgadas)",
      "suspensión_trasera": "monoamortiguador Pro-Link con cinco posiciones de ajuste de la precarga del muelle",
      "recorrido_rueda_trasera": "103 mm (4,1 pulgadas)",
      "neumático_delantero": "110/70-17 ",
      "neumático_trasero": "140/70-17 ",
      "frenos_delanteros": "Disco simple. ABS opcional",
      "frenos_traseros": "Single disc. ABS opcional",
      "peso_total": "160,6 kg (354,0 libras)",
      "altura_asiento": "780 mm (30,7 pulgadas) Si es ajustable, la posición más baja",
      "distancia entre ejes": "1379 mm (54,3 pulgadas)",
      "capacidad_combustible": "12,87 litros (3,40 galones US)",
      "arranque": "Eléctrico"
    },
    {
      "marca": "Honda",
      "modelo": "CBR500R",
      "año": "2022",
      "tipo": "Sport",
      "cilindrada": "471,0 ccm (28,74 pulgadas cúbicas)",
      "motor": "bicilíndrico, cuatro tiempos",
      "potencia": "46,9 CV (34,3 kW)) @ 8600 RPM",
      "par": "43,0 Nm (4,4 kgf-m o 31,7 ft.lbs) @ 6500 RPM",
      "compresión": "10.7:1",
      "diámetro_carrera": "67,0 x 66,8 mm (2,6 x 2,6 pulgadas)",
      "válvulas_por_cilindro": "4",
      "sistema_combustible": "Inyección PGM-FI con cuerpos de mariposa de 34 mm",
      "fuel_control": "Doble árbol de levas en cabeza/doble árbol de levas (DOHC)",
      "ignición": "Completamente transistorizado",
      "refrigeración": "Líquido",
      "caja de cambios": "6 velocidades",
      "transmisión": "Cadena (transmisión final)",
      "embrague": "Multidisco húmedo, embrague deslizante asistido",
      "consumo_combustible": "3,50 litros/100 km (28,6 km/l o 67,21 mpg)",
      "emission": "81,2 CO2 g/km. (CO2 - Emisión de dióxido de carbono) ",
      "bastidor": "Tubo de diamante de acero",
      "suspensión delantera": "Horquilla Showa 41mm SFF-BP USD, ajustable en precarga",
      "recorrido_rueda_delantera": "120 mm (4,7 pulgadas)",
      "suspensión_trasera": "Prolink mono con ajuste de precarga de 5 etapas. Basculante transversal hueco de acero",
      "recorrido_rueda_trasera": "119 mm (4,7 pulgadas)",
      "neumático_delantero": "120/70-ZR17",
      "rear_tire": "160/60-ZR17 ",
      "frenos_delanteros": "Doble disco. Disco ondulado. Pinzas de dos pistones. ABS",
      "frenos_traseros": "Disco simple. Disco ondulado. Pinza de un pistón. ABS",
      "peso_total": "190,1 kg (419,0 libras)",
      "altura_asiento": "785 mm (30,9 pulgadas) Si es ajustable, la posición más baja",
      "altura_total": "1145 mm (45,1 pulgadas)",
      "longitud_total": "2080 mm (81,9 pulgadas)",
      "total_width": "755 mm (29,7 pulgadas)",
      "distancia entre ejes": "1410 mm (55,5 pulgadas)",
      "capacidad_combustible": "17,10 litros (4,52 galones US)",
      "arranque": "Eléctrico"
    },
    {
      "marca": "Honda",
      "modelo": "CBR600RR",
      "año": "2022",
      "tipo": "Sport",
      "cilindrada": "599,0 ccm (36,55 pulgadas cúbicas)",
      "motor": "cuatro en línea, cuatro tiempos",
      "potencia": "118,0 CV (86,1 kW)) @ 13500 RPM",
      "par": "66,0 Nm (6,7 kgf-m o 48,7 ft.lbs) @ 11225 RPM",
      "compresión": "12.2:1",
      "diámetro_carrera": "67,0 x 42,5 mm (2,6 x 1,7 pulgadas)",
      "válvulas_por_cilindro": "4",
      "sistema_combustible": "Inyección. Inyección de combustible de doble etapa (DSFI) con cuerpos de mariposa de 40 mm, inyectores Denso de 12 orificios",
      "fuel_control": "Doble árbol de levas en cabeza/doble árbol de levas (DOHC)",
      "encendido": "Transistorizado digital controlado por ordenador con mapeado 3D",
      "refrigeración": "Líquido",
      "caja de cambios": "6 velocidades",
      "transmisión": "Cadena (transmisión final)",
      "consumo_combustible": "5,35 litros/100 km (18,7 km/l o 43,97 mpg)",
      "emisiones": "124,1 CO2 g/km. (CO2 - Emisión de dióxido de carbono)",
      "bastidor": "Diamante, aluminio fundido a presión",
      "suspensión_delantera": "Horquilla invertida Big Piston de 41 mm con ajuste de precarga de muelle, amortiguación de rebote y compresión",
      "recorrido_rueda_delantera": "109 mm (4,3 pulgadas)",
      "suspensión_trasera": "monoamortiguador Unit Pro-Link® HMAS™ con ajuste de precarga de muelle, rebote y amortiguación de compresión",
      "recorrido_rueda_trasera": "130 mm (5,1 pulgadas)",
      "neumático_delantero": "120/70-ZR17",
      "neumático_trasero": "180/55-ZR17 ",
      "frenos_delanteros": "Doble disco. ABS opcional. Discos flotantes. Pinzas de cuatro pistones. Montaje radial. ",
      "frenos_traseros": "Disco simple. ABS opcional. Pinza de un pistón. ",
      "peso_total": "186,0 kg (410,0 libras)",
      "altura_asiento": "820 mm (32,3 pulgadas) Si es ajustable, el ajuste más bajo",
      "longitud_total": "2029 mm (79,9 pulgadas)",
      "ancho_total": "685 mm (27.0 inches)",
      "ground_clearance": "135 mm (5,3 pulgadas)",
      "distancia entre ejes": "1369 mm (53,9 pulgadas)",
      "capacidad_combustible": "18.00 litros (4.76 galones US)",
      "arranque": "Eléctrico"
    },
    {
      "marca": "Honda",
      "modelo": "CBR650R",
      "año": "2022",
      "tipo": "Sport",
      "cilindrada": "649,0 ccm (39,60 pulgadas cúbicas)",
      "motor": "cuatro en línea, cuatro tiempos",
      "potencia": "93,9 CV (68,5 kW)) @ 12000 RPM",
      "par": "63,0 Nm (6,4 kgf-m o 46,5 ft.lbs) @ 8500 RPM",
      "compresión": "11.6:1",
      "diámetro_carrera": "67,0 x 46,0 mm (2,6 x 1,8 pulgadas)",
      "válvulas_por_cilindro": "4",
      "sistema_combustible": "Inyección PGM-FI con cuerpos de mariposa de 32 mm",
      "fuel_control": "Doble árbol de levas en cabeza/doble árbol de levas (DOHC)",
      "ignición": "Encendido transistorizado completo",
      "lubricación": "Cárter húmedo",
      "refrigeración": "Líquido",
      "caja de cambios": "6 velocidades",
      "transmisión": "Cadena (transmisión final)",
      "embrague": "Húmedo, discos múltiples. Mecánico, accionado por cable",
      "consumo_combustible": "4,90 litros/100 km (20,4 km/l o 48,00 mpg)",
      "emission": "113,7 CO2 g/km. (CO2 - Emisión de dióxido de carbono)",
      "bastidor": "diamante de acero",
      "suspensión_delantera": "Horquilla delantera Showa Separate Function Big Piston (SFF-BP) USD de 41 mm",
      "rear_suspension": "Amortiguador Monoshock con precarga ajustable en 7 etapas",
      "neumático_delantero": "120/70-17 ",
      "neumático_trasero": "180/55-17 ",
      "frenos_delanteros": "Doble disco. Pinzas de dos pistones. ABS",
      "frenos_traseros": "Disco simple. Pinza de un pistón. ABS",
      "peso_total": "208,0 kg (458,6 libras)",
      "altura_asiento": "810 mm (31,9 pulgadas) Si es ajustable, la posición más baja",
      "altura_total": "1150 mm (45,3 pulgadas)",
      "longitud_total": "2120 mm (83,5 pulgadas)",
      "total_width": "750 mm (29.5 inches)",
      "distancia_al suelo": "130 mm (5.1 inches)",
      "distancia entre ejes": "1448 mm (57,0 pulgadas)",
      "capacidad_combustible": "15,40 litros (4,07 galones US)",
      "arranque": "Eléctrico"
    }
  ]
export function MotosDatosFiltrados(){
   const scooters = motoDatos.filter(moto => moto.type === "Scooter");
   const streets = motoDatos.filter(moto => {
    if( moto.type == ("moto desnuda"||"Naked bike"||"Sport"||"Allround")){ return moto}
   });
   const offRoads = motoDatos.filter(moto => moto.type === "Enduro / offroad")
   
   const value = React.useMemo(() =>{
    return ({
     scooters,
     streets,
     offRoads   
    })
   },[scooters, streets, offRoads])
   return value 
};
